#!/bin/sh
set -e

HDPI_WIDTH=68
HDPI_HEIGHT=96

rsvg --width=$(($HDPI_WIDTH * 13)) --height=$(($HDPI_HEIGHT * 5)) paris.svg paris.png
convert -crop ${HDPI_WIDTH}x${HDPI_HEIGHT} paris.png card%d.png

mkdir -p res/drawable-hdpi

echo "0 c1
1 c2
2 c3
3 c4
4 c5
5 c6
6 c7
7 c8
8 c9
9 c10
10 cj
11 cq
12 ck
13 d1
14 d2
15 d3
16 d4
17 d5
18 d6
19 d7
20 d8
21 d9
22 d10
23 dj
24 dq
25 dk
26 h1
27 h2
28 h3
29 h4
30 h5
31 h6
32 h7
33 h8
34 h9
35 h10
36 hj
37 hq
38 hk
39 s1
40 s2
41 s3
42 s4
43 s5
44 s6
45 s7
46 s8
47 s9
48 s10
49 sj
50 sq
51 sk
52 jb
53 jr
54 bb" | while read NUM DEST; do
    mv "card$NUM.png" "res/drawable-hdpi/$DEST.png"
done

# Remove unused jokers
rm -f res/drawable-*/j*.png

# Remove empty images
rm paris.png card*.png
